export const fightRow: string;
export const fightOrder: string;
export const fighters: string;
export const fighter: string;
export const fighterName: string;
export const record: string;
export const vs: string;
export const details: string;
export const result: string;
