// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sportarr.Api.Data;

#nullable disable

namespace Sportarr.Api.Migrations
{
    [DbContext(typeof(SportarrDbContext))]
    [Migration("20260201100000_AddMonitoredEventTypes")]
    partial class AddMonitoredEventTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            // Note: This is a minimal designer file. The full model snapshot is in SportarrDbContextModelSnapshot.cs
            // This migration adds MonitoredEventTypes column to the Leagues table
#pragma warning restore 612, 618
        }
    }
}
